
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author Paula Nuñez
 */
public class Registrar extends javax.swing.JFrame {

    String user, cedula;

    public Registrar(String user, String cedula) {
        this.user = user;
        this.cedula = cedula;
        setIconImage(new ImageIcon(getClass().getResource("ICons/4Uicon.png")).getImage());
        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new custom.PanelRound();
        BtnVerifyUser = new javax.swing.JButton();
        fcedula = new javax.swing.JTextField();
        fnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnEXIT = new javax.swing.JButton();
        valid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fcontraseña = new javax.swing.JPasswordField();
        ojo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound2.setBackground(new java.awt.Color(153, 102, 255));

        BtnVerifyUser.setBackground(new java.awt.Color(38, 0, 75));
        BtnVerifyUser.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        BtnVerifyUser.setForeground(new java.awt.Color(209, 163, 255));
        BtnVerifyUser.setText("REGISTRAR");
        BtnVerifyUser.setAlignmentY(0.0F);
        BtnVerifyUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(209, 163, 255), 2, true));
        BtnVerifyUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnVerifyUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnVerifyUserMouseReleased(evt);
            }
        });
        BtnVerifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerifyUserActionPerformed(evt);
            }
        });

        fcedula.setBackground(new java.awt.Color(209, 163, 255));
        fcedula.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        fcedula.setForeground(new java.awt.Color(0, 0, 0));
        fcedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(38, 0, 75), 3, true));
        fcedula.setOpaque(true);
        fcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcedulaActionPerformed(evt);
            }
        });
        fcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fcedulaKeyTyped(evt);
            }
        });

        fnombre.setBackground(new java.awt.Color(209, 163, 255));
        fnombre.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        fnombre.setForeground(new java.awt.Color(0, 0, 0));
        fnombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(38, 0, 75), 3, true));
        fnombre.setOpaque(true);
        fnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnombreActionPerformed(evt);
            }
        });
        fnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnombreKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 0, 75));
        jLabel1.setText("Ingrese su nombre:");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 0, 75));
        jLabel2.setText("Ingrese su cédula:");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 0, 75));
        jLabel3.setText("Ingrese una contraseña:");

        BtnEXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICons/cerrrar35.png"))); // NOI18N
        BtnEXIT.setBorder(null);
        BtnEXIT.setBorderPainted(false);
        BtnEXIT.setContentAreaFilled(false);
        BtnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEXITActionPerformed(evt);
            }
        });

        valid.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        valid.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICons/Logo 4U_1.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 0, 75));
        jLabel5.setText("Registrar administrador");

        fcontraseña.setBackground(new java.awt.Color(209, 163, 255));
        fcontraseña.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        fcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        fcontraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(38, 0, 75), 3, true));
        fcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fcontraseñaMouseClicked(evt);
            }
        });
        fcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcontraseñaActionPerformed(evt);
            }
        });

        ojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICons/ojoabierto.png"))); // NOI18N
        ojo.setContentAreaFilled(false);
        ojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ojoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(BtnVerifyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound2Layout.createSequentialGroup()
                                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fcedula, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(fnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(fcontraseña))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ojo))
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(BtnEXIT)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BtnEXIT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(fcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ojo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(BtnVerifyUser)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcedulaActionPerformed
        fcedula.setText(null);
    }//GEN-LAST:event_fcedulaActionPerformed

    private void fcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fcedulaKeyTyped

        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // Ignora el carácter si no es un dígito
        }
    }//GEN-LAST:event_fcedulaKeyTyped

    private void fnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnombreActionPerformed
        fnombre.setText(null);
    }//GEN-LAST:event_fnombreActionPerformed

    private void fnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnombreKeyTyped
        char ce = evt.getKeyChar();
        if (Character.isDigit(ce)) {
            evt.consume(); // Ignora el carácter si no es un dígito
        }
    }//GEN-LAST:event_fnombreKeyTyped

    private void BtnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEXITActionPerformed

        this.dispose();

    }//GEN-LAST:event_BtnEXITActionPerformed

    private void fcontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcontraseñaMouseClicked

        fcontraseña.setText(null);
    }//GEN-LAST:event_fcontraseñaMouseClicked

    private void fcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcontraseñaActionPerformed

    private void ojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ojoActionPerformed
        char echoChar = fcontraseña.getEchoChar(); // Obtener el carácter de eco actual
        if (echoChar != 0) {
            fcontraseña.setEchoChar((char) 0); // Establecer el carácter de eco a 0 (sin ocultar)
            ojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICons/ojocerrado.png")));;
        } else {
            fcontraseña.setEchoChar('\u2022'); // Establecer el carácter de eco a • (ocultar)
            ojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICons/ojoabierto.png")));;
        }
    }//GEN-LAST:event_ojoActionPerformed

    private void BtnVerifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerifyUserActionPerformed
        BtnVerifyUser.requestFocusInWindow();
        String nombre = fnombre.getText(), ced = fcedula.getText(), contraseña = fcontraseña.getText();
        boolean registrada = false;
        String[] cUsuarios;

        try {
            BufferedReader BR = new BufferedReader(new FileReader("CedulasAdmins.txt"));
            String linea;
            while ((linea = BR.readLine()) != null) {
                System.out.println("LINEA: " + linea);
                cUsuarios = linea.split("\\| ");
                if (ced.equals(cUsuarios[1])) {
                    registrada = true;

                    break;
                }
                System.out.println("ced" + ced);
                System.out.println("cUsuarios[2]" + cUsuarios[1]);
            }

            BR.close();
        } catch (IOException ex) {
            System.out.println("Error al leer el archivo.");
            ex.printStackTrace();
        }

        if (registrada) {
            valid.setText("Cédula ya registrada.");
        } else if (!registrada) {
            if (nombre.isEmpty() || ced.isEmpty() || contraseña.isEmpty()) {
                valid.setText("Debe llenar todos los campos.");
            } else { // Guardar nuevo administrador en el archivo
                try {
                    String datos = nombre + "| " + ced + "| " + contraseña;
                    FileWriter FW = new FileWriter("CedulasAdmins.txt", true);
                    FW.write(datos + "\n");
                   
                    
                    valid.setText("Usuario registrado con éxito.");
                    
                    FW.close();
                } catch (IOException ex) {
                    System.out.println("Error al escribir en el archivo.");
                    ex.printStackTrace();
                }
            }
        }
       
    }//GEN-LAST:event_BtnVerifyUserActionPerformed

    private void BtnVerifyUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVerifyUserMouseReleased
      
    }//GEN-LAST:event_BtnVerifyUserMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEXIT;
    private javax.swing.JButton BtnVerifyUser;
    private javax.swing.JTextField fcedula;
    private javax.swing.JPasswordField fcontraseña;
    private javax.swing.JTextField fnombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton ojo;
    private custom.PanelRound panelRound2;
    private javax.swing.JLabel valid;
    // End of variables declaration//GEN-END:variables
}
